apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/adr-location: ../../../../../docs/ADR/decisions
    backstage.io/techdocs-ref: dir:.
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: batazor111@gmail.com
  lifecycle: experimental
