apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shortlink-api
  description: ShortLink API
  links:
    - url: https://github.com/shortlink-org/shortlink/tree/main/boundaries/api/api-gateway
      title: GitHub Repo
      icon: github
  tags:
    - go
  annotations:
    'backstage.io/kubernetes-namespace': shortlink
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=shortlink-api'
    backstage.io/source-location: url:https://github.com/shortlink-org/shortlink/tree/main/boundaries/api/api-gateway
    backstage.io/techdocs-ref: url:url:https://github.com/shortlink-org/shortlink/tree/main/boundaries/api/api-gateway
    prometheus.io/alert: 'Excessive Memory Usage'
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
spec:
  type: service
  lifecycle: production
  owner: shortlink-org
  system: shortlink
  providesApis:
    - shortlink-api
