apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shortlink-newsletter
  description: Notify service for ShortLink
  links:
    - url: https://github.com/shortlink-org/shortlink/tree/main/boundaries/notification/newsletter
      title: GitHub Repo
      icon: github
  tags:
    - rust
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=shortlink-newsletter'
    backstage.io/source-location: url:https://github.com/shortlink-org/shortlink/tree/main/boundaries/notification/newsletter
    backstage.io/techdocs-ref: url:url:https://github.com/shortlink-org/shortlink/tree/main/boundaries/notification/newsletter
    prometheus.io/alert: 'Excessive Memory Usage'
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
spec:
  type: service
  lifecycle: development
  owner: shortlink-org
  system: shortlink
  dependsOn:
    - resource:shortlink-newsletter-db
